apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-list-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-pods-role
subjects:
  - kind: ServiceAccount
    name: backend-serviceaccount
    namespace: mi-namespace
