apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-user-rolebinding
  namespace: mi-namespace
subjects:
  - kind: User
    name: "limited-user"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: limited-user-role
  apiGroup: rbac.authorization.k8s.io
