apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: limited-sa-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: limited-sa
    namespace: mi-namespace
roleRef:
  kind: ClusterRole
  name: limited-cluster-role
  apiGroup: rbac.authorization.k8s.io
