apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mi-namespace
  name: limited-user-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
