apiVersion: v1
kind: Namespace
metadata:
  name: mi-namespace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: mi-namespace
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      type: Container
